---

- name: First test
  gather_facts: false
  hosts: all
  vars:
    vac_event: "pwrev"
  tasks:
    - name: Validate power hysteresis
      fail: msg="'OffWatts' must be equal or lower than 'OnWatts'"
      when: (inventory_hostname in groups.machines) and (OffWatts > OnWatts)

    - name: General task
      include_role:
        name: tobias_richter.tasmota
      vars:
        tasmota_commands:
          # disable MQTT client
          - command: SetOption3
            value: 0

    - name: Machines task
      when: inventory_hostname in groups.machines
      include_role:
        name: tobias_richter.tasmota
      vars:
        vac: "{{ groups['vacuum'][0] }}"
        vac_usr: "{{ hostvars[vac]['tasmota_user'] | default('') | urlencode }}"
        vac_pw: "{{ hostvars[vac]['tasmota_password'] | default('') | urlencode }}"
        vac_auth: "{{ (vac_usr == '' or vac_pw == '') | ternary('', '&user='+vac_usr+'&password='+vac_pw) }}"
        tasmota_commands:
          # create notification rule
          - command: Rule1
            value: ON ENERGY#Power>{{ OnWatts }} DO
                     WebSend [{{ vac }}] /cm?cmnd=event%20{{ vac_event }}=1{{ vac_auth }}
                   ENDON
                   ON ENERGY#Power<{{ OffWatts }} DO
                     WebSend [{{ vac }}] /cm?cmnd=event%20{{ vac_event }}=0{{ vac_auth }}
                   ENDON
          # enable "run once" feature
          - command: Rule1
            value: 5
          # enable rule execution
          - command: Rule1
            value: 1
          # save current power on/off state (for restoring upon reboot)
          - command: SetOption0
            value: 1
          # restore last power on/off state (default; TODO: Rethink!)
          - command: PowerOnState
            value: 3
          # enable modem sleep (default)
          - command: SetOption127
            value: 0

    - name: Vacuum task
      when: inventory_hostname in groups.vacuum
      include_role:
        name: tobias_richter.tasmota
      vars:
        tasmota_commands:
          - command: Rule1
            value: ON System#Boot DO
                     var1 0
                   ENDON
                   ON Event#{{ vac_event }}=1 DO
                     Backlog
                       add1 1;
                       event trig
                   ENDON
                   ON Event#{{ vac_event }}=0 DO
                     Backlog
                       sub1 1;
                       event trig
                   ENDON
                   ON Event#trig DO
                     event trval1=%var1%
                   ENDON
                   ON Event#trval1>0 DO
                     Power On
                   ENDON
                   ON Event#trval1<=0 DO
                     Backlog
                       Power Off;
                       var1 0
                   ENDON
                   ON Power1#State=0 DO
                     var1 0
                   ENDON
          # enable rule execution
          - command: Rule1
            value: 1
          # do not save current power on/off state (for restoring upon reboot)
          - command: SetOption0
            value: 0
          # keep power off upon reboot
          - command: PowerOnState
            value: 0
          # enable modem sleep (default)
          - command: SetOption127
            value: 0  # (1 only if we see major Wifi delays)

